import Head from "next/head";
import Navbar from "components/Navbar";
import SignUpClient from "components/SignUpClient";

const cliente = () => {
    return (
        <>
            <Head>
                <title>Meu mediador</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/house-favicon.svg" />
            </Head>

            <Navbar />

            <SignUpClient />
        </>
    );
};

export default cliente;