import Head from "next/head";
import { useRouter } from "next/router";
import { ReactNode,useEffect, useState } from "react";
import Navbar from "../Navbar";
import Footer from "../Footer";
import RenderConditional from "../RenderConditional";
import * as C from './styles'

type LayoutProps = {
  children: ReactNode;
};

export default function Layout({ children }: LayoutProps) {
  const [path, setPath] = useState<string>("");
  const [loading, setLoading] = useState<boolean>(true);
  const [isMobile, setIsMobile] = useState<boolean>(false);
  const router = useRouter();
  const RenderFooter = path === "/" ? null : <Footer />

  useEffect(() => {
    setPath(router.pathname);
    const initialLoaderTimeout = 1500;

    setTimeout(() => {
      setLoading(false);
    }, initialLoaderTimeout);
  }, [router]);

  useEffect(() => {
    const handleResize = () => {
      setIsMobile(window.innerWidth < 768);
    };

    handleResize();

    window.addEventListener("resize", handleResize);

    return () => {
      window.removeEventListener("resize", handleResize);
    };
  }, []);

  return (
    <C.Container className={path === "/" ? "home" : ""}>
      <Head>
        <title>Meoagent</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/meoagent-favicon.png" />
        <link rel="preload" href="/meoagent-logo.png" as="image" />
        <link rel="preload" href="/sublogo.png" as="image" />
      </Head>

      <RenderConditional isTrue={loading}>
        <C.LoaderContainer>
            <div className="spinner"/>
          </C.LoaderContainer>
      </RenderConditional>
            <Navbar>
                {children}
                {RenderFooter}
            </Navbar>
    </C.Container>
  );
}
