import Head from "next/head";
import Navbar from './Navbar';

export default function Layout({ children }) {
    return (
        <>
            <Head>
                <title>Meu mediador</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/house-favicon.svg" />
            </Head>

            <Navbar />
            <main>{children}</main>
        </>
    )
}