export type MyProfileRealtor = {
    firstName: string,
    lastName: string,
    photo: string,
    contact: string,
    email: string,
    whatsapp: string,
    languages: string,
    description: string,
    site: string,
    facebook: string,
    instagram: string,
    twitter: string,
    currentJobPlace: string,
    areas: string,
    housesToSale: string,
    oldJobPlaces: string,
    courseName: string,
    courseDescription: string,
    rewardName: string,
    rewardDescription: string,
    specializationName: string,
    specializationDescription: string,
    services: string
}