import Head from 'next/head'
// import Image from 'next/image'
// import { Inter } from '@next/font/google'
// import styles from '@/styles/Home.module.css'


// const inter = Inter({ subsets: ['latin'] })

import Navbar from 'components/Navbar';
import FindRealtor from 'components/FindRealtor';

export default function Home() {
  return (
    <>
      <Head>
        <title>Meu mediador</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <FindRealtor />
    </>
  )
}
