import Head from 'next/head'
import Navbar from 'components/Navbar';
import FindRealtor from 'components/FindRealtor';

export default function Home() {
  return (
    <>
      <Head>
        <title>Meu mediador</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/house-favicon.svg" />
      </Head>

      <Navbar />

      <FindRealtor />
    </>
  )
}
